import Foundation

let machine = PetStateMachine()
assert(machine.state == .idle)
assert(machine.send(.randomWalk) && machine.state == .walk)
assert(machine.send(.dragStart) && machine.state == .dragged)
assert(!machine.send(.mouseNear) && machine.state == .dragged)
assert(!machine.send(.click) && machine.state == .dragged)
assert(machine.send(.dragEnd) && machine.state == .idle)
assert(machine.send(.mouseNear) && machine.state == .approachMouse)
assert(!machine.send(.mouseMiddle) && machine.state == .approachMouse)
assert(machine.send(.mouseFar) && machine.state == .idle)
assert(machine.send(.sleepCommand) && machine.state == .drowsy)
assert(machine.send(.animationEnded) && machine.state == .sleep)
assert(machine.send(.wake) && machine.state == .wakeUp)
assert(machine.send(.animationEnded) && machine.state == .idle)
assert(machine.send(.doubleClick) && machine.state == .doubleClickReaction)
assert(machine.send(.landed) && machine.state == .idle)
print("PetStateMachine smoke test passed")
